'use strict';

/**
 * @ngdoc object
 * @name op.translate.translateConfig
 * @description
 *
 * This is the translateConfig config file
 *
 */
angular.module('op.translate').constant('translateConfig', {
    googleTranslate: {
        languages: [
            { title: 'English', value: 'en' },
            { title: 'Spanish', value: 'es' },
            { title: 'Afrikaans', value: 'af' },
            { title: 'Albanian', value: 'sq' },
            { title: 'Arabic', value: 'ar' },
            { title: 'Armenian', value: 'hy' },
            { title: 'Azerbaijani', value: 'az' },
            { title: 'Basque', value: 'eu' },
            { title: 'Belarusian', value: 'be' },
            { title: 'Bengali', value: 'bn' },
            { title: 'Bosnian', value: 'bs' },
            { title: 'Bulgarian', value: 'bg' },
            { title: 'Catalan', value: 'ca' },
            { title: 'Cebuano', value: 'ceb' },
            { title: 'Chichewa', value: 'ny' },
            { title: 'Chinese Simplified', value: 'zh-CN' },
            { title: 'Chinese Traditional', value: 'zh-TW' },
            { title: 'Croatian', value: 'hr' },
            { title: 'Czech', value: 'cs' },
            { title: 'Danish', value: 'da' },
            { title: 'Dutch', value: 'nl' },
            { title: 'Esperanto', value: 'eo' },
            { title: 'Estonian', value: 'et' },
            { title: 'Filipino', value: 'tl' },
            { title: 'Finnish', value: 'fi' },
            { title: 'French', value: 'fr' },
            { title: 'Galician', value: 'gl' },
            { title: 'Georgian', value: 'ka' },
            { title: 'German', value: 'de' },
            { title: 'Greek', value: 'el' },
            { title: 'Gujarati', value: 'gu' },
            { title: 'Haitian Creole', value: 'ht' },
            { title: 'Hausa', value: 'ha' },
            { title: 'Hebrew', value: 'iw' },
            { title: 'Hindi', value: 'hi' },
            { title: 'Hmong', value: 'hmn' },
            { title: 'Hungarian', value: 'hu' },
            { title: 'Icelandic', value: 'is' },
            { title: 'Igbo', value: 'ig' },
            { title: 'Indonesian', value: 'id' },
            { title: 'Irish', value: 'ga' },
            { title: 'Italian', value: 'it' },
            { title: 'Japanese', value: 'ja' },
            { title: 'Javanese', value: 'jw' },
            { title: 'Kannada', value: 'kn' },
            { title: 'Kazakh', value: 'kk' },
            { title: 'Khmer', value: 'km' },
            { title: 'Korean', value: 'ko' },
            { title: 'Lao', value: 'lo' },
            { title: 'Latin', value: 'la' },
            { title: 'Latvian', value: 'lv' },
            { title: 'Lithuanian', value: 'lt' },
            { title: 'Macedonian', value: 'mk' },
            { title: 'Malagasy', value: 'mg' },
            { title: 'Malay', value: 'ms' },
            { title: 'Malayalam', value: 'ml' },
            { title: 'Maltese', value: 'mt' },
            { title: 'Maori', value: 'mi' },
            { title: 'Marathi', value: 'mr' },
            { title: 'Mongolian', value: 'mn' },
            { title: 'Myanmar (Burmese)', value: 'my' },
            { title: 'Nepali', value: 'ne' },
            { title: 'Norwegian', value: 'no' },
            { title: 'Persian', value: 'fa' },
            { title: 'Polish', value: 'pl' },
            { title: 'Portuguese', value: 'pt' },
            { title: 'Punjabi', value: 'ma' },
            { title: 'Romanian', value: 'ro' },
            { title: 'Russian', value: 'ru' },
            { title: 'Serbian', value: 'sr' },
            { title: 'Sesotho', value: 'st' },
            { title: 'Sinhala', value: 'si' },
            { title: 'Slovak', value: 'sk' },
            { title: 'Slovenian', value: 'sl' },
            { title: 'Somali', value: 'so' },
            { title: 'Sudanese', value: 'su' },
            { title: 'Swahili', value: 'sw' },
            { title: 'Swedish', value: 'sv' },
            { title: 'Tajik', value: 'tg' },
            { title: 'Tamil', value: 'ta' },
            { title: 'Telugu', value: 'te' },
            { title: 'Thai', value: 'th' },
            { title: 'Turkish', value: 'tr' },
            { title: 'Ukrainian', value: 'uk' },
            { title: 'Urdu', value: 'ur' },
            { title: 'Uzbek', value: 'uz' },
            { title: 'Vietnamese', value: 'vi' },
            { title: 'Welsh', value: 'cy' },
            { title: 'Yiddish', value: 'yi' },
            { title: 'Yoruba', value: 'yo' },
            { title: 'Zulu', value: 'zu' }
        ]
    }
});
